apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
  namespace: default
spec:
  selector:
    app: ecommerce
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer