apiVersion: v1
kind: Pod
metadata:
  name: mysql-curl-pod
  namespace: default
  labels:
    app: mysql-curl # Add this label
spec:
  containers:
    - name: mysql-curl-container
      image: ubuntu:latest
      command: ["/bin/bash", "-c", "apt-get update && apt-get install -y mysql-client curl python3 && python3 -m http.server 8080"]
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
        requests:
          cpu: "200m"
          memory: "256Mi"