apiVersion: v1
kind: Service
metadata:
  name: mysql-curl-service
  namespace: default
spec:
  selector:
    app: mysql-curl # Must match a label on the pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP # Use NodePort or LoadBalancer for external access